name: Validate Bicep Templates

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID || secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID || secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID || secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true # Optional: set to true if you don't need a subscription
          
      - name: Install Bicep CLI
        run: |
          az bicep version || az bicep install
          az bicep version
      
      - name: Validate Module Templates
        run: |
          echo "Validating Bicep modules..."
          find ./modules -name "main.bicep" | while read template; do
            echo "Validating $template"
            az bicep build --file "$template"
          done
      
      - name: Validate Example Templates
        run: |
          echo "Validating Bicep examples..."
          find ./examples -name "*.bicep" | while read template; do
            echo "Validating $template"
            az bicep build --file "$template"
          done
